# =============================================================================
# seahub_settings.py — Seahub web UI configuration
# =============================================================================
# Written by:  seafile-config-fixes.sh / update.sh
# Deployed to: $SEAFILE_VOLUME/seafile/conf/seahub_settings.py
#              (inside the seafile container via volume mount)
#
# REFERENCE FILE — variables like ${SEAFILE_DOMAIN} are substituted from .env
# at deploy time by the script. Do not edit this file to change your deployment;
# edit /opt/seafile/.env and re-run update.sh instead.
#
# Non-standard vs default Seafile seahub_settings.py:
#   - Collabora Online configured (OFFICE_SERVER_TYPE, WOPI_ACCESS_TOKEN_EXPIRATION,
#     OFFICE_WEB_APP_*). Seafile does not enable this by default.
#   - CACHES uses django_redis pointing at the internal redis container.
#     Default Seafile 13 Docker wires Redis via .env but does not write the
#     explicit CACHES dict; we write it for clarity and correctness.
#   - ENABLE_METADATA_MANAGEMENT and METADATA_SERVER_URL enable the extended
#     properties feature backed by the seafile-metadata sidecar container.
#   - FILE_PREVIEW_MAX_SIZE raised to 30 MB (Seafile default is lower).
#   - COMPRESS_ENABLED = True reduces page load size.
#   - SECRET_KEY is preserved from any existing file so sessions survive re-runs.
# =============================================================================

# -*- coding: utf-8 -*-
SECRET_KEY = "${EXISTING_KEY}"
TIME_ZONE = '${SEAFILE_TIMEZONE}'

# --- Collabora Online ---
# OFFICE_WEB_APP_BASE_URL must be the public-facing URL of your Seafile server.
# The browser contacts this URL directly — using an internal Docker hostname here
# will break the WebSocket connection when opening documents.
OFFICE_SERVER_TYPE = 'CollaboraOffice'
ENABLE_OFFICE_WEB_APP = True
OFFICE_WEB_APP_BASE_URL = 'https://${SEAFILE_DOMAIN}/hosting/discovery'
WOPI_ACCESS_TOKEN_EXPIRATION = 30 * 60
OFFICE_WEB_APP_FILE_EXTENSION = ('odp', 'ods', 'odt', 'xls', 'xlsb', 'xlsm', 'xlsx', 'ppsx', 'ppt', 'pptm', 'pptx', 'doc', 'docm', 'docx')
ENABLE_OFFICE_WEB_APP_EDIT = True
OFFICE_WEB_APP_EDIT_FILE_EXTENSION = ('odp', 'ods', 'odt', 'xls', 'xlsb', 'xlsm', 'xlsx', 'ppsx', 'ppt', 'pptm', 'pptx', 'doc', 'docm', 'docx')

# --- Redis Cache ---
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': '${REDIS_URL}',
        'TIMEOUT': 86400,
    }
}

# --- File Handling ---
FILE_PREVIEW_MAX_SIZE = 30 * 1024 * 1024
COMPRESS_ENABLED = True

# --- Metadata / Extended Properties ---
# Requires metadata-server container running and [METADATA] enabled in seafevents.conf.
# After enabling here, go into each library → Settings → toggle on Extended Properties.
ENABLE_METADATA_MANAGEMENT = True
METADATA_SERVER_URL = 'http://metadata-server:8084'
